version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
